import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FixedBar from "@/components/ui/FixedBar";
import { ThemeProvider } from "@/components/theme-provider";
import { notFound } from "next/navigation";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (    
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased w-screen h-dvh max-h-dvh flex flex-col bg-zinc-100 dark:bg-neutral-900 dark:text-zinc-300`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem          
          disableTransitionOnChange          
        >        
          <div className="flex-1 overflow-y-scroll">
            {children}
          </div>          
          <FixedBar/>
        </ThemeProvider>
      </body>
    </html>
  );
}
